// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJgnK_uYmnrtKu-gIJiOyUoKgYzZethg',
    appId: '1:195021946956:web:01fbd031c0f51a842b34e9',
    messagingSenderId: '195021946956',
    projectId: 'testtraining-61361',
    authDomain: 'testtraining-61361.firebaseapp.com',
    storageBucket: 'testtraining-61361.appspot.com',
    measurementId: 'G-8TN3L2QNTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA66YizZ1ikLrCcXBECjaMRpOYog2P6IQc',
    appId: '1:195021946956:android:c1c52753c2bf76322b34e9',
    messagingSenderId: '195021946956',
    projectId: 'testtraining-61361',
    storageBucket: 'testtraining-61361.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ4EKfwum93YlIA1K12DeQbjzdiyEBGkQ',
    appId: '1:195021946956:ios:2230b924fa2d3dfe2b34e9',
    messagingSenderId: '195021946956',
    projectId: 'testtraining-61361',
    storageBucket: 'testtraining-61361.appspot.com',
    iosClientId: '195021946956-74nr20igqu3ih4pv8uee1j3hr4abjmvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.testtraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ4EKfwum93YlIA1K12DeQbjzdiyEBGkQ',
    appId: '1:195021946956:ios:2230b924fa2d3dfe2b34e9',
    messagingSenderId: '195021946956',
    projectId: 'testtraining-61361',
    storageBucket: 'testtraining-61361.appspot.com',
    iosClientId: '195021946956-74nr20igqu3ih4pv8uee1j3hr4abjmvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.testtraining',
  );
}
